# Generated by Django 3.2.18 on 2023-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
